# Site settings
title: "CSSwatch"
email: hi@zeb.codes
description: CSS color names
baseurl: ""
url: "http://zebapy.github.io/swatch"
twitter_username: zebhdiyah
github_username: zebapy
author_url: "http://zeb.codes"

# Build settings
markdown: kramdown
