# Site settings
title: "Swatch &middot; CSS Color Names"
email: hi@zeb.codes
description: "CSS color names in hexidecimal, RGB, and HSL formats."
baseurl: "/swatch"
url: "http://zebapy.github.io/swatch"
github_url: "https://github.com/zebapy/swatch"
twitter_username: zebhdiyah
github_username: zebapy
author_url: "http://zeb.codes"

# Build settings
markdown: kramdown
